task:
  name: Build sbtn for macOS ARM64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  coursier_cache:
    folder: $HOME/Library/Caches/Coursier/v1
  sbt_cache:
    folder: $HOME/.sbt
  build_script: arch -arm64 ./.cirrus/publish-macos-silicon.sh
  binary_artifacts:
    name: Binary assets
    path: "sbt/client/target/bin/sbtn"
  env:
    GITHUB_TOKEN: ENCRYPTED[83e802f6a62a961dcd89603793151c17679bed510f18b4f9e583da7fd6265e983dad5d690c9440100ad1901f20e23ae7]
